/* The contents of this file will be copied unmodified to the top of your build. */

// change me
CURRENT_LOG_LEVEL = 3;
// change me
LOG_FLAIR = true;

// AI CONSTANT VALUES - DO NOT CHANGE

LOG_NONE = 0;
LOG_ERROR = 1;
LOG_INFO = 2;
LOG_VERBOSE = 3;

ENERGIZE_RANGE = 200;
MUSTER_RANGE = 100;
SPIRIT_SPEED = 20;

// AI BEHAVIOUR VALUES - CHANGE ME!!
INITIAL_ATTACK_WAVE_SIZE = 15;
MIN_ATTACK_ENERGY = 0.4;
HARVESTER_AGGRESSION_RANGE = ENERGIZE_RANGE * 1.25;
DEFENDER_AGGRESSION_RANGE = ENERGIZE_RANGE * 1.5;
MIN_DEDICATED_MINERS = 5;
